version: '3.8'

services:
  archon-server:
    image: hl-harbor.techpad.uk/archon/archon-server:latest
    ports:
      - "8181:8181"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN}
      - LOG_LEVEL=INFO
      - HOST=0.0.0.0
      - ARCHON_SERVER_PORT=8181
      - ARCHON_MCP_PORT=8051
      - ARCHON_AGENTS_PORT=8052
      - ARCHON_UI_PORT=3737
      - ARCHON_EMBEDDINGS_PORT=8080
      - EMBEDDING_DIMENSIONS=1536
      - EMBEDDING_MODEL_ID=sentence-transformers/all-MiniLM-L6-v2
    networks:
      - archon-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  archon-mcp:
    image: hl-harbor.techpad.uk/archon/archon-mcp:latest
    ports:
      - "8051:8051"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN}
      - LOG_LEVEL=INFO
    networks:
      - archon-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8051/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  archon-agents:
    image: hl-harbor.techpad.uk/archon/archon-agents:latest
    ports:
      - "8052:8052"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN}
      - LOG_LEVEL=INFO
    networks:
      - archon-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8052/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  archon-ui:
    image: hl-harbor.techpad.uk/archon/archon-ui:latest
    ports:
      - "3737:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=https://archon-api.techpad.uk
      - VITE_MCP_BASE_URL=https://archon-mcp.techpad.uk
    networks:
      - archon-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  archon-embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.8
    ports:
      - "8080:80"
    environment:
      - MODEL_ID=sentence-transformers/all-MiniLM-L6-v2
      - MAX_CONCURRENT_REQUESTS=512
      - MAX_BATCH_TOKENS=16384
      - MAX_BATCH_REQUESTS=32
    networks:
      - archon-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  archon-network:
    driver: overlay
    attachable: true

configs:
  archon_env:
    external: true

secrets:
  supabase_service_key:
    external: true
  logfire_token:
    external: true
